import path from "path";
import type { Config, SiteAnalysis, BrandVoice, AnalyzeResult } from "../types.js";
import { fetchPage, extractMainContent, extractMetadata, extractLinks } from "../utils/fetcher.js";
import { generateJsonWithClaude } from "../utils/claude.js";
import { getSiteOutputDir, getDomainFromUrl } from "../utils/config.js";
import { writeMarkdown, writeJson } from "../utils/storage.js";

const ANALYSIS_SYSTEM_PROMPT = `You are an expert brand strategist and content analyst. Your task is to analyze website content and extract key information about the brand, voice, audience, and topics.

Analyze the provided website content and return a JSON object with this exact structure:

{
  "name": "Company/Brand name",
  "description": "One sentence description of what they do",
  "industry": "Primary industry/sector",
  "targetAudience": ["audience segment 1", "audience segment 2"],
  "valuePropositions": ["value prop 1", "value prop 2", "value prop 3"],
  "keyTopics": ["topic 1", "topic 2", "topic 3", "topic 4", "topic 5"],
  "brandVoice": {
    "tone": "professional|casual|technical|friendly|authoritative",
    "formality": "formal|semi-formal|informal",
    "vocabulary": ["key terms they use"],
    "sentenceStyle": "Description of their writing style",
    "avoidWords": ["words to avoid based on their style"],
    "examplePhrases": ["characteristic phrases from their content"]
  }
}

Be specific and base all analysis on the actual content provided.`;

export async function analyzeSite(
  url: string,
  config: Config
): Promise<AnalyzeResult> {
  const domain = getDomainFromUrl(url);
  const outputDir = getSiteOutputDir(config, url);

  // Fetch main page
  const mainHtml = await fetchPage(url);
  const mainContent = extractMainContent(mainHtml);
  const metadata = extractMetadata(mainHtml);
  const links = extractLinks(mainHtml, url);

  // Fetch additional pages for better analysis
  const pagesToFetch = [
    links.find((l) => /about/i.test(l)),
    links.find((l) => /services?/i.test(l)),
    links.find((l) => /products?/i.test(l)),
    links.find((l) => /solutions?/i.test(l)),
  ].filter(Boolean) as string[];

  let additionalContent = "";
  for (const pageUrl of pagesToFetch.slice(0, 3)) {
    try {
      const html = await fetchPage(pageUrl);
      additionalContent += "\n\n---\n\n" + extractMainContent(html);
      await sleep(config.rateLimit);
    } catch {
      // Skip failed pages
    }
  }

  const fullContent = `
URL: ${url}
Title: ${metadata.title}
Description: ${metadata.description}
Keywords: ${metadata.keywords.join(", ")}

Main Content:
${mainContent}

Additional Pages:
${additionalContent}
`.trim();

  // Analyze with Claude
  const analysisData = await generateJsonWithClaude<Omit<SiteAnalysis, "url" | "domain" | "analyzedAt">>(
    config,
    ANALYSIS_SYSTEM_PROMPT,
    `Analyze this website content:\n\n${fullContent}`
  );

  const analysis: SiteAnalysis = {
    url,
    domain,
    ...analysisData,
    analyzedAt: new Date().toISOString(),
  };

  // Generate blog-plan.md
  const blogPlan = generateBlogPlanMarkdown(analysis);
  const planPath = path.join(outputDir, "blog-plan.md");
  await writeMarkdown(planPath, blogPlan);

  // Save analysis JSON
  await writeJson(path.join(outputDir, "site-analysis.json"), analysis);

  return { analysis, planPath };
}

function generateBlogPlanMarkdown(analysis: SiteAnalysis): string {
  return `# Blog Strategy: ${analysis.name}

> Generated by Blog Builder on ${new Date().toLocaleDateString()}
> Source: ${analysis.url}

---

## Brand Overview

**Industry:** ${analysis.industry}

**Description:** ${analysis.description}

### Target Audience
${analysis.targetAudience.map((a) => `- ${a}`).join("\n")}

### Value Propositions
${analysis.valuePropositions.map((v) => `- ${v}`).join("\n")}

### Key Topics
${analysis.keyTopics.map((t) => `- ${t}`).join("\n")}

---

## Brand Voice

**Tone:** ${analysis.brandVoice.tone}

**Formality:** ${analysis.brandVoice.formality}

**Writing Style:** ${analysis.brandVoice.sentenceStyle}

### Vocabulary to Use
${analysis.brandVoice.vocabulary.map((v) => `- ${v}`).join("\n")}

### Example Phrases
${analysis.brandVoice.examplePhrases.map((p) => `> "${p}"`).join("\n\n")}

### Words to Avoid
${analysis.brandVoice.avoidWords.map((w) => `- ${w}`).join("\n")}

---

## Content Inventory

_Run \`blog-builder discover ${analysis.url}\` to catalog existing articles_

---

## Recommended Articles

_Run \`blog-builder plan ${analysis.url}\` to generate article recommendations_

---

## Next Steps

1. Review this brand analysis for accuracy
2. Run \`blog-builder discover\` to find existing content
3. Run \`blog-builder plan\` to generate article briefs
4. Run \`blog-builder generate\` to create articles
5. Review and publish to Medium/LinkedIn

---

_Generated by [Blog Builder](https://github.com/dbbuilder-org/blog-builder)_
`;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
